############################
## CHANGE THESE
############################

baseURL: "https://fabricadasaudade.github.io/new_website"
title: new_website

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
